### ISSUE TITLE
Windows 10, Node 7.-x Npm 4.x - npm run build or npm start fails with same error

### ISSUE THREAD

**Issue by HansS** [btroncone/ngrx-store-localstorage#35]
> rxheroes@1.0.0 build:dev c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes
> webpack --config config/webpack.dev.js --progress --profile --colors --display-error-details --display-cached
                                                                                                                                                                            4129ms o 90% optimize assetsError: Debug Failure. False expression: File  has unknown extension.
    at Object.assert (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:3323:23)
    at Object.fail (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:3328:19)
    at Object.extensionFromPath (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:3470:15)
    at c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:66803:46
    at Array.map (native)
    at resolveModuleNamesWorker (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:66797:141)
    at resolveModuleNamesReusingOldState (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:66924:24)
    at processImportedModules (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:67834:35)
    at findSourceFile (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:67744:17)
    at processImportedModules (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:67863:25)
    at findSourceFile (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:67744:17)
    at processImportedModules (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:67863:25)
    at findSourceFile (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:67744:17)
    at processSourceFile (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:67647:27)
    at processRootFile (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:67535:13)
    at c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:66825:60
    at Object.forEach (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:1443:30)
    at Object.createProgram (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:66825:16)
    at synchronizeHostData (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:85978:33)
    at Object.getProgram (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\typescript\lib\typescript.js:86079:13)
    at State.updateProgram (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\awesome-typescript-loader\dist.babel\host.js:241:42)
    at c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\awesome-typescript-loader\dist.babel\instance.js:333:27
    at Compiler.<anonymous> (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\awesome-typescript-loader\dist.babel\instance.js:354:15)
    at Compiler.next (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\tapable\lib\Tapable.js:69:14)
    at Compiler.<anonymous> (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\webpack\lib\CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\tapable\lib\Tapable.js:71:13)
    at Compiler.<anonymous> (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\webpack\lib\Compiler.js:400:9)
    at Compilation.<anonymous> (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\webpack\lib\Compilation.js:577:13)
    at Compilation.next (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\tapable\lib\Tapable.js:67:11)
    at Compilation.<anonymous> (c:\Users\Folio\web\frontend\javascript\frameworks\angular-rxjs\rxheroes\node_modules\webpack\lib\ProgressPlugin.js:69:5)

**Comment by ernestomancebo** [comment]
how is this related to ngrx-store-localstorage?
